/* ============================================================================
   ♫ MAVOmusic MASTER PLAYLISTS - THIS IS THE ONLY FILE YOU EDIT FOR SONGS ♫
   ----------------------------------------------------------------------------
   Every screen on the site reads THESE two lists. The home page counts the
   entries automatically ("Total videos in the spotlight").

   HOW TO ADD A SONG (takes 20 seconds):
   1. Open this file in Notepad (or any editor).
   2. Copy any line below, paste it at the bottom of the right list
      (BEFORE the line that says "add new entries ABOVE this line").
   3. Replace the link and the title. Keep the  { url: "...", title: "..." },
      shape - curly braces, quotes and the comma at the end.
   4. Save (plain save, Ctrl+S is enough).
   5. ONLINE EDIT (the normal way since V2.4): do steps 1-4 right on GitHub -
      github.com/MAVOmusic/mavomusic-site → playlists.js → pencil icon →
      Commit changes. The live site reads THIS file from GitHub and updates
      itself within ~10 minutes. No uploads, no zips, works from your phone.
      (Typo paranoia? Relax: if the online file ever has a broken line, the
      site quietly keeps using its last good packaged copy until you fix it.)
   6. PC EDIT (rare): edit this local copy, then upload it into the repo
      (repo page → Add file → Upload files → drag playlists.js → Commit).

   Links can be pasted in ANY of these shapes - the site finds the ID itself:
     https://youtu.be/XXXXXXXXXXX
     https://www.youtube.com/watch?v=XXXXXXXXXXX
     https://youtube.com/shorts/XXXXXXXXXXX?feature=share
     or even just the bare ID: XXXXXXXXXXX

   Titles: keep the quotes straight (" not ”). Apostrophes are fine.
   Batches welcome: 100 pasted lines are just 100 lines. 🎸
   ============================================================================ */

// 🎬 LONG-FORM - full videos
const MAVO_LONGS = [
  { url: "https://youtu.be/RJbqxu-0c4s", title: "Fieldy's signature low-tuned clank tone on 'Twisted Transistor' defined 2000s nu-metal!" },
  { url: "https://youtu.be/C1CSv-hkZa8", title: "Deep emotional alternative-rock bass dynamics on Avril Lavigne's 'How Does It Feel'!" },
  { url: "https://youtu.be/JrRFxCJ5JCw", title: "Rammstein's industrial bass giant: Oliver Riedel's iconic 'Du Hast'!" },
  { url: "https://youtu.be/pX7LsLTXYSk", title: "Bill Hamilton's driving post-hardcore bass engine on 2005's 'My Heroine'!" },
  { url: "https://youtu.be/FrKIcnvQzNo", title: "Reworking Depeche Mode's electronic riff through Johnny Cash's dark acoustic drive!" },
  { url: "https://youtu.be/VNGJyDUQ0_4", title: "Guiding early-2000s melodic rock basslines on the Thunderbird!" },
  { url: "https://youtu.be/JrCRrSKn0tA", title: "Jeremy Davis's heavy alternative rock bass dynamics on Paramore's 'All I Wanted'!" },
  { url: "https://youtu.be/JJdzVz-rKIo", title: "High-speed Monstercat gaming electro-rock basslines on four strings!" },
  { url: "https://youtu.be/URokI0gCA3k", title: "Francis Buchholz's smooth, anthemic rock bassline on 'Wind Of Change'!" },
  { url: "https://youtu.be/5Kau4keX15c", title: "Adapting South African zef rave synth-bass to physical strings!" },
  { url: "https://youtu.be/N2SjxyBPYLI", title: "Shavo Odadjian's emotional Drop-C bass foundation on 'Lonely Day'!" },
  { url: "https://youtu.be/0bsuAm6_yrQ", title: "Christian Giesler's thrash metal precision low-end drive on Kreator's 'Enemy Of God'!" },
  { url: "https://youtu.be/UA_BbQZf4LI", title: "Jay's deep 1996 hip-hop bass groove parodying 'Gangsta's Paradise'!" },
  { url: "https://youtu.be/6jsZF9WIAtw", title: "Subtle, delicate low-end acoustic support on Rammstein's ambient closer!" },
  { url: "https://youtu.be/vX0uSspk8Bs", title: "90s emo pioneer Jawbreaker built this masterpiece around deep bass dynamics!" },
  { url: "https://youtu.be/zEG2qxqEDzc", title: "Unstoppable 2007 pop-punk bass attack on 'Misery Business'!" },
  { url: "https://youtu.be/yx09Po0EFtc", title: "This 2013 pop-punk anthem has a surprisingly driving low-end core!" },
  { url: "https://youtu.be/jnysCCBFHxs", title: "Steve Currie's swaggering 1973 glam-rock bass riff on '20th Century Boy'!" },
  { url: "https://youtu.be/aiiQVkZ0JRM", title: "Jack Bruce's revolutionary 1968 psych-rock bass improvisations!" },
  { url: "https://youtu.be/GglA-J9dQ_M", title: "Heaviest ultra-low Drop-tuning bass assault in modern Rammstein history!" },
  { url: "https://youtu.be/T1zt9RMbWgA", title: "Transforming Monstercat Uncaged dubstep bass drops to physical strings!" },
  { url: "https://youtu.be/S4u2IPzenf4", title: "Dark, romantic industrial metal low-end dynamics on Rammstein's 'Amour'!" },
  { url: "https://youtu.be/ZyMgqcClDZ8", title: "Riedel's atmospheric, heavy 90s industrial bass pulse on 'Alter Mann'!" },
  { url: "https://youtu.be/3vm1Y7O0rUM", title: "Brooding, heavy industrial metal basslines off Rosenrot!" },
  { url: "https://youtu.be/Ynd9TJxtImA", title: "Marching through Oliver Riedel's heavy satirical industrial metal groove!" },
  { url: "https://youtu.be/FDOKsQ1TDBg", title: "Grooving through this underground indie-rock gem with heavy bass!" },
  { url: "https://youtu.be/UY5x2sKNqpA", title: "Berry Oakley's legendary fluid 12-bar blues-rock bass walking lines!" },
  { url: "https://youtu.be/86E6T8ajOTg", title: "Classic 1970s TV theme walking basslines played with vintage feel!" },
  { url: "https://youtu.be/AHpKtDQ8XXM", title: "Prince-written 80s pop-rock basslines played with a crisp low-end attack!" },
  { url: "https://youtu.be/ALx6jAM7ndQ", title: "Paul Ryder's Madchester funk-house bassline is an absolute dancefloor classic!" },
  { url: "https://youtu.be/VFQ9biuvT7M", title: "Joe Osborn's studio Wrecking Crew 1966 sunshine pop bassline!" },
  { url: "https://youtu.be/r3zNdgk0hyg", title: "Heavy industrial guitar riffing backed by Oliver Riedel's relentless bass pulse!" },
  { url: "https://youtu.be/VRvYugHbL8c", title: "Pete Briquette's melodic new wave bass runs on 'I Don't Like Mondays'!" },
  { url: "https://youtu.be/c8r3PVGwi9E", title: "Oliver Riedel's crushing Drop-C industrial metal bass weight on 'Adieu'!" },
  { url: "https://youtu.be/y-nefH75OLs", title: "Johnny Christ's theatrical bass work on 'A Little Piece Of Heaven' is wild!" },
  { url: "https://youtu.be/iValDY9_Bm0", title: "Michael Todd's catchy prog-pop bass hook on 'A Favor House Atlantic'!" },
  { url: "https://youtu.be/T-L7yXBHBow", title: "Adding a live Thunderbird bassline over 2008 crunkcore synth 808s!" },
  { url: "https://youtu.be/UOquV5qhlbQ", title: "Jeff Ament's soulful 1991 grunge bassline on 'Hunger Strike'!" },
  { url: "https://youtu.be/MBxSWeE-OkE", title: "Rob Kucharek's driving 2004 pop-punk bass engine on 'The 12th Day'!" },
  { url: "https://youtu.be/yMSnji-sYmQ", title: "Devouring the heaviest, most chaotic metalcore breakdown about pizza!" },
  { url: "https://youtu.be/IJWkKnqq_NY", title: "Zia McCabe's driving 2000s garage-rock indie bass groove!" },
  { url: "https://youtu.be/-RsXcyvptk0", title: "Drifting through the atmospheric, rolling bass foundation of Pendulum's 9,000 Miles!" },
  { url: "https://youtu.be/ikWMaUqdkHs", title: "Injecting thunderous analog bass into FINNEAS's iconic 2019 pop groove!" },
  { url: "https://youtu.be/8gxR5p9srto", title: "Sprinting through 175 BPM of pure melodic death metal and drum & bass on my Thunderbird!" },
  { url: "https://youtu.be/Vvfi6klJ3n0", title: "Nobody talks about how bouncy this 1979 New Wave bassline is!" },
  { url: "https://youtu.be/WRTdEvM7E5g", title: "Nate Mendel's heaviest Foo Fighters riff is an absolute bass masterclass!" },
  { url: "https://youtu.be/KVSvH0z4ukU", title: "Huey Lewis hid a ridiculously bouncy bassline in this 80s hit!" },
  { url: "https://youtu.be/Cp-e9u0kSu8", title: "Rick Springfield's 'Jessie's Girl' has a SECRETLY brilliant bassline!" },
  { url: "https://youtu.be/XRYBtUGueDY", title: "When your stream viewer writes a song and you have to play the bass!" },
  { url: "https://youtu.be/GFcxIwjLx_g", title: "Gary Wright's synth hit has the smoothest bass groove of the 70s!" },
  { url: "https://youtu.be/FlIglT7Rk3g", title: "Trying to lock in with Tim Commerford's heaviest bass riff!" },
  { url: "https://youtu.be/Y5s4jAWLiBY", title: "Japanese post-hardcore has no business having bass riffs THIS fast!" },
  { url: "https://youtu.be/CYh5SffJGuI", title: "The bassline on 'Juicebox' has absolutely no business being this good!" },
  { url: "https://youtu.be/Twzh_faeWDo", title: "Playing bass over this classic crunkcore track is wild!" },
  { url: "https://youtu.be/Pd6COKTFM7I", title: "Why this simple Strokes bassline feels SO good to play!" },
  { url: "https://youtu.be/nRs6v6iYY9U", title: "Chris Steele's Alexisonfire bassline is pure early-2000s energy!" },
  { url: "https://youtu.be/qOBRdR-2Es0", title: "Can a bass guitar survive this legendary Joe Satriani guitar shred?" },
  { url: "https://youtu.be/DshGU1bvn50", title: "Shavo wrote SOAD's darkest, most beautiful bassline on Hypnotize!" },
  { url: "https://youtu.be/P7YI-_zTgpY", title: "Sting's bassline on 'Roxanne' is an absolute reggae-rock masterpiece!" },
  { url: "https://youtu.be/-B0YSFf1DBQ", title: "Prog bass just doesn't get more syncopated than this Dear Hunter track!" },
  { url: "https://youtu.be/BkLUukrIaYA", title: "Dennis Dunaway's glam-rock strut is Alice Cooper's secret weapon!" },
  { url: "https://youtu.be/JBXtELAR0RQ", title: "John Deacon's bassline on 'Killer Queen' is secretly a masterpiece!" },
  { url: "https://youtu.be/kohaefGF_1A", title: "Cranking up Dave Parsons's most 90s grunge bass riff ever!" },
  { url: "https://youtu.be/KRTX6x1DdUQ", title: "That Scott Walker bassline sampled by Jay-Z is unreal!" },
  { url: "https://youtu.be/KGFPHLZbRhg", title: "Michel van Schie's funkiest Dutch bass groove is pure fingerstyle speed!" },
  { url: "https://youtu.be/X-AXAAnwBWg", title: "Simonon wrote the heaviest reggae-punk bassline of 1979!" },
  { url: "https://youtu.be/VIea7UbRSpY", title: "Stomping through The Clash's most iconic punk rock bassline!" },
  { url: "https://youtu.be/xuKAi0sDBdU", title: "Bouncing through the most uplifting bassline of 2013!" },
  { url: "https://youtu.be/5B6M3VKySGI", title: "Dr. Dre crafted the ultimate hip-hop bassline for 50 Cent!" },
  { url: "https://youtu.be/9ABXMOTgugg", title: "Anime basslines demand high-speed fingerstyle stamina!" },
  { url: "https://youtu.be/qPBDE4xSrrM", title: "Discovering the breeziest indie-pop bassline of 2010!" },
  { url: "https://youtu.be/G1FB5XeJyF0", title: "Rocking out to the ultimate 2000s pop-punk anthem!" },
  { url: "https://youtu.be/SIAe4cu-m5w", title: "Getting down with Donald \"Duck\" Dunn's greatest bassline!" },
  { url: "https://youtu.be/chQURW5E1ck", title: "Melodic hardcore basslines don't get much better than this!" },
  { url: "https://youtu.be/GrQeI8UjO84", title: "Deacon's legendary arena-rock bass tone is massive!" },
  { url: "https://youtu.be/OfRwTx-XSZw", title: "Nailing the syncopated rhythm of this pop-punk anthem!" },
  { url: "https://youtu.be/awYtnx6cGOM", title: "Forging a Christmas classic into a heavy metal bass workout!" },
  { url: "https://youtu.be/bc4RY2QCDTs", title: "Translating aggressive cello metal directly to the bass guitar!" },
  { url: "https://youtu.be/9Nev0wfhJ-0", title: "Digging into some heavy indie-punk riffs from New Jersey!" },
  { url: "https://youtu.be/AAnaTfGnmSs", title: "Jamming the most famous soul bassline of the 1960s!" },
  { url: "https://youtu.be/BNuZTgSdu0Q", title: "Revisiting the golden age of 2000s post-hardcore bass!" },
  { url: "https://youtu.be/aAMxYp8s6xw", title: "Dave Parsons' hypnotic grunge bassline is a 90s masterpiece!" },
  { url: "https://youtu.be/UaCfbXlaYxQ", title: "Fueling the ultimate 1980s arena pop anthem!" },
  { url: "https://youtu.be/njnzF3BlcGU", title: "Zeppelin's secret weapon wrote the ultimate twisted blues-rock riff!" },
  { url: "https://youtu.be/OmMBaIIBIx8", title: "Pumping out the aggressive funk-pop bassline that launched Maroon 5!" },
  { url: "https://youtu.be/OQK2RzRYCjE", title: "Driving through the ultimate 1999 skate-punk anthem!" },
  { url: "https://youtu.be/lSii1UiGSIk", title: "Hammering some heavy 2007 metalcore riffs on the bass!" },
  { url: "https://youtu.be/rGM3RFtrDBs", title: "Speeding through the fastest J-punk bassline on my channel!" },
  { url: "https://youtu.be/ytr8AfH5mJQ", title: "Exploring the craziest math-rock indie groove from 2012!" },
  { url: "https://youtu.be/2mK3LVDwDX4", title: "Channeling the iconic pop-punk intro of Blink-182's Dammit!" },
  { url: "https://youtu.be/69MbzLyuDug", title: "Mastering the dark, horror-punk basslines of AFI's Totalimmortal!" },
  { url: "https://youtu.be/kZI4P6-gtgs", title: "Chugging through the heavy proto-metal roots of The Kinks!" },
  { url: "https://youtu.be/WdFoqKEq6B0", title: "V-Man's dark gothic-metal basslines on 'Killpop' are heavy!" },
  { url: "https://youtu.be/-jQ0wVn8BIk", title: "Locking into the ultimate 2000s rap-metal club anthem!" },
  { url: "https://youtu.be/q04lN7t8EXg", title: "Kiss's 1975 arena-rock bassline on 'Rock And Roll All Nite'!" },
  { url: "https://youtu.be/M2cxmiBmDzU", title: "Unfiltered garage-rock bass on The Vines' 'Get Free'!" },
  { url: "https://youtu.be/Z8JgXVrwEgA", title: "Caroling through Brian Adam McCune's 'God Rest Ye Merry, Gentlemen'!" },
  { url: "https://youtu.be/SlRj79VrdJg", title: "Underdog bass energy from Good Charlotte's 'A New Beginning'!" },
  { url: "https://youtu.be/tkPBN0rQeI8", title: "[📺] Rocksmith 2014 Bass Cover – Otis Redding - (Sittin' On) The Dock Of The.. | Live Stream Gameplay" },
  // 👉 add new long-form entries ABOVE this line
];

// 📱 SHORTS - vertical bites
const MAVO_SHORTS = [
  { url: "https://youtube.com/shorts/dGr8fRWzZh4?feature=share", title: "Fieldy's iconic low-tuned Korn clank bass tone!" },
  { url: "https://youtube.com/shorts/uy8UbkQoA1E?feature=share", title: "Brooding 2000s alt-rock low-end depth on bass!" },
  { url: "https://youtube.com/shorts/yyyoo4wFiNA?feature=share", title: "Most recognizable industrial metal bassline in history!" },
  { url: "https://youtube.com/shorts/YOtThBM_9X0?feature=share", title: "Acoustic blues-rock low end on Johnny Cash's cover!" },
  { url: "https://youtube.com/shorts/oKgHsrIF_fY?feature=share", title: "Peak 2005 post-hardcore bass drive from Silverstein!" },
  { url: "https://youtube.com/shorts/8mMy5COYn3w?feature=share", title: "Soaring 2004 alt-rock bass drive with huge hooks!" },
  { url: "https://youtube.com/shorts/n7nKcNUnfGE?feature=share", title: "Alternative rock low-end surge on Paramore's biggest crescendo!" },
  { url: "https://youtube.com/shorts/X36Ai0R1kGA?feature=share", title: "Monstercat gaming electro-rock bass drops on physical strings!" },
  { url: "https://youtube.com/shorts/hmIZHkPnERc?feature=share", title: "1990 rock ballad low-end foundation from Scorpions!" },
  { url: "https://youtube.com/shorts/4Ftdo4M_CHU?feature=share", title: "Rave synth 808s translated directly to a bass guitar!" },
  { url: "https://youtube.com/shorts/LXgDtGR9cKc?feature=share", title: "Shavo's haunting Drop-C low-end support on 'Lonely Day'!" },
  { url: "https://youtube.com/shorts/8OAqYzUj6q8?feature=share", title: "190 BPM German thrash metal bass intensity!" },
  { url: "https://youtube.com/shorts/j58UArq-t0Q?feature=share", title: "Parodying 90s hip-hop bass groove on 'Amish Paradise'! #shorts #bass" },
  { url: "https://youtube.com/shorts/l9CFRhtLGDo?feature=share", title: "Gentle ambient low-end warmth from Rammstein!" },
  { url: "https://youtube.com/shorts/K0mBsLZv4ik?feature=share", title: "Emo-pioneer 90s basslines that built a genre!" },
  { url: "https://youtube.com/shorts/pnqw_ODOiws?feature=share", title: "Pure 2007 pop-punk bass energy from Paramore!" },
  { url: "https://youtube.com/shorts/Ds0QjuPoKNU?feature=share", title: "High-octane pop-punk bass energy on 'A Love Like War'! #shorts #bass" },
  { url: "https://youtube.com/shorts/bm2kcYom2RY?feature=share", title: "Relentless 1981 power-pop bass pulse on a Thunderbird! #shorts #bass" },
  { url: "https://youtube.com/shorts/cgnEvwUFA3Q?feature=share", title: "1973 glam-rock swaggering bass riff from T. Rex! #shorts #bass" },
  { url: "https://youtube.com/shorts/mej4DUXemyQ?feature=share", title: "Jack Bruce's wild 60s blues-rock bass wizardry! #shorts #bass" },
  { url: "https://youtube.com/shorts/zUAByfwWXDw?feature=share", title: "Ultra-heavy Drop-tuning metal power from Rammstein! #shorts #bass" },
  { url: "https://youtube.com/shorts/rOO5-33H_2o?feature=share", title: "Monstercat Uncaged dubstep bass drops on real bass guitar! #shorts #bass" },
  { url: "https://youtube.com/shorts/z32nFVkdsfk?feature=share", title: "Romantic industrial love-metal bass depth on a Thunderbird! #shorts #bass" },
  { url: "https://youtube.com/shorts/9j9qYuJKP4s?feature=share", title: "Haunting 90s German industrial metal bass foundation! #shorts #bass" },
  { url: "https://youtube.com/shorts/w3lsOrUdpJY?feature=share", title: "Dark industrial metal bass drive on 'Hilf Mir'! #shorts #bass" },
  { url: "https://youtube.com/shorts/urhxSfYoWk8?feature=share", title: "Stomping 2004 industrial metal bass punch on 'Amerika'! #shorts #bass" },
  { url: "https://youtube.com/shorts/cCMoGN3BAnE?feature=share", title: "Underground indie bass riff with serious fingerstyle punch! #shorts #bass" },
  { url: "https://youtube.com/shorts/fbtmNHHZUEY?feature=share", title: "Masterclass in 12-bar blues-rock walking bass lines! #shorts #bass" },
  { url: "https://youtube.com/shorts/FcK1NqCEO2k?feature=share", title: "Vintage 70s walking pop-rock bassline from 'Happy Days'! #shorts #bass" },
  { url: "https://youtube.com/shorts/8-87HQ9Lha8?feature=share", title: "Bright 1986 pop-rock bass drive written by Prince! #shorts #bass" },
  { url: "https://youtube.com/shorts/odlGJ-_i9K8?feature=share", title: "90s UK Madchester funk bass groove that refuses to quit! #shorts #bass" },
  { url: "https://youtube.com/shorts/PQFysfZ_N1s?feature=share", title: "Wrecking Crew 1966 sunshine pop bass masterclass! #shorts #bass" },
  { url: "https://youtube.com/shorts/zT8fuSftO0g?feature=share", title: "Industrial metal bass aggression on Rammstein's 'Adios'! #shorts #bass" },
  { url: "https://youtube.com/shorts/hFFhZQHcxqU?feature=share", title: "1979 UK new wave melodic bass runs on a Thunderbird! #shorts #bass" },
  { url: "https://youtube.com/shorts/kAIQYzDc9zI?feature=share", title: "Crushing German industrial metal Drop-C low end! #shorts #bass" },
  { url: "https://youtube.com/shorts/0F5bMviMpzs?feature=share", title: "Orchestral metal madness on Avenged Sevenfold's darkest track! #shorts #bass" },
  { url: "https://youtube.com/shorts/RiVqajmtwgI?feature=share", title: "P03 prog-punk bassline that sticks in your head for days! #shorts #bass" },
  { url: "https://youtube.com/shorts/G7eGc_uPdfo?feature=share", title: "Crunkcore synth 808s paired with real distorted bass guitar! #shorts #bass" },
  { url: "https://youtube.com/shorts/MhRLy8yJS0g?feature=share", title: "Jeff Ament's legendary 1991 grunge bass tone! #shorts #bass" },
  { url: "https://youtube.com/shorts/y5K45rJ3hQY?feature=share", title: "Driving early-2000s skate punk bass sprint! #shorts #bass" },
  { url: "https://youtube.com/shorts/E_-W-HzzETU?feature=share", title: "Feasting on the heaviest metalcore breakdown ever written about pizza! #shorts #bass" },
  { url: "https://youtube.com/shorts/rS5XBxfWXNQ?feature=share", title: "Indie garage-rock bass drive on 'Bohemian Like You'! #shorts #bass" },
  { url: "https://youtube.com/shorts/vrd8kpcn0lE?feature=share", title: "Gliding through this atmospheric 2008 drum & bass groove! #shorts #bass" },
  { url: "https://youtube.com/shorts/O7gLBJxjnNk?feature=share", title: "Pulsing through that instantly recognizable 2019 pop bass hook! #shorts #bass" },
  { url: "https://youtube.com/shorts/EBx7tUtpNxg?feature=share", title: "Drum & bass meets Swedish metal forearm endurance! #shorts #bass" },
  { url: "https://youtube.com/shorts/MJk1FHGyRDs?feature=share", title: "Nobody expects this much bounce from a 1979 New Wave bassline! #shorts #bass" },
  { url: "https://youtube.com/shorts/MBh1-b939Rk?feature=share", title: "Drop-in moment: Nate Mendel's heaviest Foo Fighters riff hits! #shorts #bass" },
  { url: "https://youtube.com/shorts/0TpvZj-tnKs?feature=share", title: "Warning: this 80s Huey Lewis bassline bounces WAY too hard! #shorts #bass" },
  { url: "https://youtube.com/shorts/qkjNd1u-4ZQ?feature=share", title: "1981 pop-rock bass that drives the entire song! #shorts #bass" },
  { url: "https://youtube.com/shorts/4AY4BpuKwMk?feature=share", title: "Stream viewer makes a song, you lay down the bass! #shorts #bass" },
  { url: "https://youtube.com/shorts/nqNe2LYrzH0?feature=share", title: "Smooth 70s synth-rock bass drift at its finest! #shorts #bass" },
  { url: "https://youtube.com/shorts/teutbHZkzgM?feature=share", title: "Tim Commerford's RATM bass tone is pure fury! #shorts #bass" },
  { url: "https://youtube.com/shorts/dkn2gsbsgY4?feature=share", title: "Finger-melting Japanese J-Rock bass speed ahead! #shorts #bass" },
  { url: "https://youtube.com/shorts/He_ByBZOVUA?feature=share", title: "This Strokes bassline is an absolute garage rock masterpiece! #shorts #bass" },
  { url: "https://youtube.com/shorts/RMq5_y3TQ1I?feature=share", title: "Adding real bass to a wild crunkcore banger! #shorts #bass" },
  { url: "https://youtube.com/shorts/_zUYx9DeEtw?feature=share", title: "Everyone recognizes that 2000s indie bassline instantly! #shorts #bass" },
  { url: "https://youtube.com/shorts/HI_-FUbvtak?feature=share", title: "2004 post-hardcore low-end energy is UNREAL! #shorts #bass" },
  { url: "https://youtube.com/shorts/P12Pz8wfeTk?feature=share", title: "Attempting Satch Boogie on FOUR STRINGS?! #shorts #bass" },
  { url: "https://youtube.com/shorts/nFBJMntaL5c?feature=share", title: "SOAD's haunting drop-C bass hits different every time! #shorts #bass" },
  { url: "https://youtube.com/shorts/9FAasfJaK7o?feature=share", title: "Grooving hard on Sting's iconic reggae-rock pocket! #shorts #bass" },
  { url: "https://youtube.com/shorts/JKhTmCiTMXQ?feature=share", title: "Prog bass syncopation that genuinely breaks your brain! #shorts #bass" },
  { url: "https://youtube.com/shorts/aX5RatJhD-8?feature=share", title: "Plucking out Alice Cooper's glam-rock bass strut live! #shorts #bass" },
  { url: "https://youtube.com/shorts/ilSYMSodDL4?feature=share", title: "John Deacon's Queen bass work is impossibly elegant! #shorts #bass" },
  { url: "https://youtube.com/shorts/jYtcWmZXaRE?feature=share", title: "1994 Bush grunge bass riff — pure nostalgia power! #shorts #bass" },
  { url: "https://youtube.com/shorts/Bl3MOsUJbZM?feature=share", title: "The 1969 Scott Walker bassline sampled by Jay-Z! #shorts #bass" },
  { url: "https://youtube.com/shorts/CgSd5Ys0wiM?feature=share", title: "Unleashing that Dutch funk-pop bass live on stream! #shorts #bass" },
  { url: "https://youtube.com/shorts/o3WKV-oQ2GQ?feature=share", title: "Simonon's reggae-punk masterpiece on the Thunderbird! #shorts #bass" },
  { url: "https://youtube.com/shorts/Wi096gdzaEg?feature=share", title: "Classic 1982 punk energy on the Thunderbird! #shorts #bass" },
  { url: "https://youtube.com/shorts/79rrOO-5MFs?feature=share", title: "Uplifting 2013 pop-rock energy on the Thunderbird! #shorts #bass" },
  { url: "https://youtube.com/shorts/B87KxNyFMdg?feature=share", title: "Taking a 2003 club anthem and making it heavy! #shorts #bass" },
  { url: "https://youtube.com/shorts/edTa__3XARo?feature=share", title: "Furious J-Rock fingerstyle on the Thunderbird! #shorts #bass" },
  { url: "https://youtube.com/shorts/9bnrIxdeI6c?feature=share", title: "Catchy jangle-pop bass grooves on the Thunderbird! #shorts #bass" },
  { url: "https://youtube.com/shorts/BtFN6yXjVkA?feature=share", title: "Reliving the golden era of pop-punk! #shorts #bass" },
  { url: "https://youtube.com/shorts/Ec-QGE2gdmI?feature=share", title: "Legendary 70s soul energy on the Thunderbird! #shorts #bass" },
  { url: "https://youtube.com/shorts/tU0jP8hV8m8?feature=share", title: "Punk rock stamina test on the Thunderbird! #shorts #bass" },
  { url: "https://youtube.com/shorts/3HGvAeKU2nQ?feature=share", title: "Holding down the ultimate stadium rock anthem! #shorts #bass" },
  { url: "https://youtube.com/shorts/UBILibgz13A?feature=share", title: "Swinging through Fall Out Boy's biggest bassline! #shorts #bass" },
  { url: "https://youtube.com/shorts/3vttr7iUrWY?feature=share", title: "Festive metal holiday vibes on an Epiphone Thunderbird! #shorts #bass" },
  { url: "https://youtube.com/shorts/2IIB2MHeWDI?feature=share", title: "Symphonic metal cello riffs on a real bass! #shorts #bass" },
  { url: "https://youtube.com/shorts/dxbfnEqnj0Q?feature=share", title: "Crunchy indie-punk basslines in Eb Drop Db! #shorts #bass" },
  { url: "https://youtube.com/shorts/ubTYEW3qE-o?feature=share", title: "Jamming the ultimate 1960s Motown bass groove! #shorts #bass" },
  { url: "https://youtube.com/shorts/Zt82X-Pa3ug?feature=share", title: "Fast post-hardcore fingerstyle on the Thunderbird! #shorts #bass" },
  { url: "https://youtube.com/shorts/1DCvbb0iRXg?feature=share", title: "Falling into the most hypnotic grunge bass groove of 1994! #shorts #bass" },
  { url: "https://youtube.com/shorts/3jBZI09b7C0?feature=share", title: "Massive 80s arena-rock vibes on the Thunderbird! #shorts #bass" },
  { url: "https://youtube.com/shorts/Ul8BEh0sQRw?feature=share", title: "Navigating Led Zeppelin's trickiest rhythmic riff! #shorts #bass" },
  { url: "https://youtube.com/shorts/fUY89KuDX08?feature=share", title: "Funky early 2000s attitude on the Thunderbird! #shorts #bass" },
  { url: "https://youtube.com/shorts/x3VfrV2Igzw?feature=share", title: "Unstoppable 1999 pop-punk energy! #shorts #bass" },
  { url: "https://youtube.com/shorts/7orfmvvPYW0?feature=share", title: "Aggressive dropped-tuned metalcore on the Thunderbird! #shorts #bass" },
  { url: "https://youtube.com/shorts/w8CxA7BO8Vo?feature=share", title: "Lightning fast J-Rock grooves! #shorts #bass" },
  { url: "https://youtube.com/shorts/o4xAVFEnvhw?feature=share", title: "Joyful indie math-rock riffs! #shorts #bass" },
  { url: "https://youtube.com/shorts/FRx2ivrk0yw?feature=share", title: "Iconic 1997 pop-punk skate vibes! #shorts #bass" },
  { url: "https://youtube.com/shorts/PZvN-EKCt54?feature=share", title: "Horror-punk bass energy on AFI's Totalimmortal! #shorts #bass" },
  { url: "https://youtube.com/shorts/gHDBc8eEXDw?feature=share", title: "Proto-metal garage rock from 1964! #shorts #bass" },
  { url: "https://youtube.com/shorts/8H6JE_dQq60?feature=share", title: "Gothic metal grooves on Slipknot's 'Killpop'! #shorts #bass" },
  { url: "https://youtube.com/shorts/I-UR0jp1VVk?feature=share", title: "Bouncy 2000s rap-metal vibes on the Thunderbird! #shorts #bass" },
  { url: "https://youtube.com/shorts/mVZgA4XEo5A?feature=share", title: "Fist-pumping bass energy on Kiss's 'Rock And Roll All Nite'! #shorts #bass" },
  { url: "https://youtube.com/shorts/REKYRWr-yMM?feature=share", title: "Ragged 2000s garage-rock bass in The Vines' 'Get Free'! #shorts #bass" },
  { url: "https://youtube.com/shorts/PPNEXg5gRMY?feature=share", title: "Yuletide bass on Brian Adam McCune's 'God Rest Ye Merry, Gentlemen'! #shorts #bass" },
  { url: "https://youtube.com/shorts/ejoXnqCm1fo?feature=share", title: "Restless Good Charlotte bass on 'A New Beginning'! #shorts #bass" },
  { url: "https://youtube.com/shorts/Ao_bOaxH9QU?feature=share", title: "[⚡] Rocksmith Bass – (Sittin' On) The Dock Of... (Otis Redding) | Full Cover Linked #rocksmith #bass" },
  // 👉 add new shorts entries ABOVE this line
];

/* Screens read the lists through these globals. No need to ever touch below. */
window.MAVO_LONGS = MAVO_LONGS;
window.MAVO_SHORTS = MAVO_SHORTS;
